name = "qudup-waitlist-api"
main = "worker/index.js"
compatibility_date = "2023-05-18"

# Configure KV namespace binding
kv_namespaces = [
  { binding = "WAITLIST_KV", id = "${KV_NAMESPACE_ID}" }
]

# Add CORS handling to allow requests from all Cloudflare Pages domains
[vars]
ALLOWED_ORIGINS = "*.pages.dev,*.cloudflare.com"  # Add your custom domains here if needed