name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Build frontend
        run: npm run build
          
      - name: Ensure _redirects file exists
        run: |
          if [ ! -f dist/public/_redirects ]; then
            echo "/* /index.html 200" > dist/public/_redirects
          fi
        
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: qudup-waitlist
          directory: dist/public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}