name: Deploy QudUP to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Full Application
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Install Wrangler
        run: npm install -g wrangler
      
      # First deploy the Worker backend
      - name: Deploy Worker
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          KV_NAMESPACE_ID: ${{ secrets.KV_NAMESPACE_ID }}
      
      # Then build and deploy the frontend
      - name: Build frontend
        run: npm run build
          
      - name: Ensure _redirects file exists
        run: |
          mkdir -p dist/public
          if [ ! -f dist/public/_redirects ]; then
            echo "/* /index.html 200" > dist/public/_redirects
          fi
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: qudup-waitlist
          directory: dist/public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Output deployment info
        run: |
          echo "✅ Déploiement terminé!"
          echo "Worker URL: https://qudup-waitlist-api.${CLOUDFLARE_WORKER_SUBDOMAIN}.workers.dev"
          echo "Frontend URL: https://qudup-waitlist.pages.dev"
        env:
          CLOUDFLARE_WORKER_SUBDOMAIN: ${{ vars.CLOUDFLARE_WORKER_SUBDOMAIN || 'your-username' }}